# Generated by Django 3.2.16 on 2023-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('s_id', models.AutoField(db_column='S_id', primary_key=True, serialize=False)),
                ('s_type', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
    ]
