# Generated by Django 3.2.16 on 2023-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('movie_name', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
    ]
