# Generated by Django 3.2.16 on 2023-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(db_column='Login_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('u_id', models.IntegerField(db_column='U_ID')),
                ('type', models.CharField(db_column='Type', max_length=20)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
