# Generated by Django 3.2.16 on 2023-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.AutoField(db_column='M_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('runtime', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('likes', models.CharField(max_length=50)),
                ('trailer', models.CharField(max_length=250)),
                ('poster', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
